# -*- coding: utf-8 -*-
"""AQI_Models_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153F3PSTl-KUxzXN1CCMUi0Iv0rX6n4bX

# AQI Prediction — Model Comparison Notebook
**Dataset:** Air Quality ML Dataset — Gurugram  
**Target:** AQI (continuous, regression)  
**Models:** Linear Regression · Random Forest · LSTM · SVM · ANN  
**Goal:** Train, evaluate and compare all five models to identify the best for future development
"""

# Install required libraries (run once)
# !pip install pandas numpy matplotlib seaborn scikit-learn openpyxl tensorflow

# Verify key libraries
import importlib, subprocess, sys

required = {
    'pandas': 'pandas',
    'numpy': 'numpy',
    'matplotlib': 'matplotlib',
    'seaborn': 'seaborn',
    'sklearn': 'scikit-learn',
    'tensorflow': 'tensorflow',
    'openpyxl': 'openpyxl',
}

missing = []
for mod, pkg in required.items():
    try:
        importlib.import_module(mod)
        print(f'  ✓ {pkg}')
    except ImportError:
        print(f'  ✗ {pkg}  ← missing')
        missing.append(pkg)

if missing:
    print(f'\nInstalling: {missing}')
    subprocess.check_call([sys.executable, '-m', 'pip', 'install'] + missing + ['-q'])
    print('Done. Please restart the kernel then re-run.')
else:
    print('\nAll dependencies present. Ready to run!')

"""---
## 1. Setup & Imports
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from matplotlib.patches import FancyBboxPatch

# Sklearn
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error,
    r2_score, mean_absolute_percentage_error
)

# TensorFlow / Keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    LSTM, Dense, Dropout, BatchNormalization
)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam

# Reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Plot style
plt.rcParams.update({
    'figure.dpi': 120,
    'axes.spines.top': False,
    'axes.spines.right': False,
    'font.family': 'DejaVu Sans',
    'axes.titlesize': 13,
    'axes.labelsize': 11,
})
PALETTE = ['#4C72B0', '#55A868', '#C44E52', '#8172B2', '#CCB974']

print(f'TensorFlow version : {tf.__version__}')
print(f'NumPy version      : {np.__version__}')
print(f'Pandas version     : {pd.__version__}')

"""---
## 2. Load & Explore Data
"""

df = pd.read_excel('Air_Quality_ML_Dataset(gurugram).xlsx')
print(f'Shape: {df.shape}')
df.head()

print('=== Data Types ===')
print(df.dtypes)
print('\n=== Null Counts ===')
print(df.isnull().sum())
print('\n=== AQI Statistics ===')
print(df['AQI'].describe())

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# AQI distribution
axes[0].hist(df['AQI'], bins=30, color=PALETTE[0], edgecolor='white', linewidth=0.5)
axes[0].set_title('AQI Distribution')
axes[0].set_xlabel('AQI')
axes[0].set_ylabel('Frequency')

# AQI category breakdown
cat_counts = df['AQI_Category'].value_counts()
colors_cat = ['#55A868','#4C72B0','#CCB974','#C44E52','#8172B2','#8B4513']
axes[1].bar(cat_counts.index, cat_counts.values,
            color=colors_cat[:len(cat_counts)], edgecolor='white')
axes[1].set_title('AQI Category Counts')
axes[1].set_xlabel('Category')
axes[1].tick_params(axis='x', rotation=30)

# AQI over time
axes[2].plot(df['date'], df['AQI'], color=PALETTE[0], linewidth=0.8, alpha=0.8)
axes[2].set_title('AQI Over Time')
axes[2].set_xlabel('Date')
axes[2].set_ylabel('AQI')
axes[2].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.show()

# Correlation heatmap — numeric columns only
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
corr = df[numeric_cols].corr()

fig, ax = plt.subplots(figsize=(14, 10))
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, linewidths=0.3, ax=ax,
            annot_kws={'size': 7})
ax.set_title('Feature Correlation Matrix', pad=15)
plt.tight_layout()
plt.show()

"""---
## 3. Feature Engineering & Preprocessing
"""

# ── Feature selection ──────────────────────────────────────────────────────
# Use raw pollutants + meteorological features as inputs.
# Exclude sub-index columns (PM2.5_si etc.) — they directly compute AQI
# and would cause data leakage.

POLLUTANTS   = ['pm2_5_ugm3', 'pm10_ugm3', 'co_ugm3', 'no2_ugm3', 'so2_ugm3', 'o3_ugm3', 'dust_ugm3']
METEO        = ['humidity_percent', 'dew_point_c', 'wind_gusts_kmh',
                'precipitation_mm', 'pressure_msl_hpa', 'cloud_cover_percent']
TEMPORAL     = ['month']
CAT_FEATURES = ['season', 'time_of_day', 'day_name']
TARGET       = 'AQI'

# Encode categorical columns
df_model = df.copy()
le = LabelEncoder()
for col in CAT_FEATURES:
    df_model[col + '_enc'] = le.fit_transform(df_model[col].astype(str))

# Boolean → int
for col in ['is_weekend', 'is_raining', 'heavy_rain']:
    df_model[col] = df_model[col].astype(int)

FEATURE_COLS = (POLLUTANTS + METEO + TEMPORAL +
                [c + '_enc' for c in CAT_FEATURES] +
                ['is_weekend', 'is_raining', 'heavy_rain'])

X = df_model[FEATURE_COLS].values
y = df_model[TARGET].values

print(f'Features : {len(FEATURE_COLS)}')
print(f'Samples  : {len(y)}')
print(f'Target   : mean={y.mean():.1f}, std={y.std():.1f}, min={y.min()}, max={y.max()}')

# ── Train / Validation / Test split (70 / 15 / 15) ──────────────────────
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, random_state=42)
X_val,   X_test, y_val,   y_test = train_test_split(X_temp, y_temp, test_size=0.50, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_val_sc   = scaler.transform(X_val)
X_test_sc  = scaler.transform(X_test)

# Reshape for LSTM → (samples, timesteps=1, features)
X_train_3d = X_train_sc.reshape(X_train_sc.shape[0], 1, X_train_sc.shape[1])
X_val_3d   = X_val_sc.reshape(X_val_sc.shape[0],   1, X_val_sc.shape[1])
X_test_3d  = X_test_sc.reshape(X_test_sc.shape[0], 1, X_test_sc.shape[1])
# ANN uses 2D (X_train_sc / X_val_sc / X_test_sc directly)

n_features = X_train_sc.shape[1]

print(f'Train : {X_train_sc.shape}  |  Val : {X_val_sc.shape}  |  Test : {X_test_sc.shape}')

# ── Helper: evaluation metrics ───────────────────────────────────────────
def evaluate(name, y_true, y_pred):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2   = r2_score(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred) * 100
    print(f'  MAE  : {mae:.3f}')
    print(f'  RMSE : {rmse:.3f}')
    print(f'  R²   : {r2:.4f}')
    print(f'  MAPE : {mape:.2f}%')
    return {'Model': name, 'MAE': mae, 'RMSE': rmse, 'R2': r2, 'MAPE': mape}

results = []  # collect all model results here

"""---
## 4. Model 1 — Linear Regression
"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_sc, y_train)

y_pred_lr_train = lr.predict(X_train_sc)
y_pred_lr_test  = lr.predict(X_test_sc)

print('Linear Regression — Test Set')
results.append(evaluate('Linear Regression', y_test, y_pred_lr_test))

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].scatter(y_test, y_pred_lr_test, alpha=0.5, color=PALETTE[0], s=20)
lims = [min(y_test.min(), y_pred_lr_test.min()), max(y_test.max(), y_pred_lr_test.max())]
axes[0].plot(lims, lims, 'r--', linewidth=1)
axes[0].set_xlabel('Actual AQI')
axes[0].set_ylabel('Predicted AQI')
axes[0].set_title('Linear Regression — Actual vs Predicted')

residuals = y_test - y_pred_lr_test
axes[1].scatter(y_pred_lr_test, residuals, alpha=0.5, color=PALETTE[0], s=20)
axes[1].axhline(0, color='red', linestyle='--', linewidth=1)
axes[1].set_xlabel('Predicted AQI')
axes[1].set_ylabel('Residual')
axes[1].set_title('Linear Regression — Residuals')

plt.tight_layout()
plt.show()

# Feature coefficients
coef_df = pd.DataFrame({'Feature': FEATURE_COLS, 'Coefficient': lr.coef_})
coef_df = coef_df.reindex(coef_df['Coefficient'].abs().sort_values(ascending=False).index)

fig, ax = plt.subplots(figsize=(10, 5))
colors = [PALETTE[0] if c > 0 else PALETTE[2] for c in coef_df['Coefficient']]
ax.barh(coef_df['Feature'], coef_df['Coefficient'], color=colors)
ax.axvline(0, color='black', linewidth=0.8)
ax.set_title('Linear Regression — Feature Coefficients')
ax.set_xlabel('Coefficient Value')
plt.tight_layout()
plt.show()

"""---
## 5. Model 2 — Random Forest Regressor
"""

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train_sc, y_train)

y_pred_rf_train = rf.predict(X_train_sc)
y_pred_rf_test  = rf.predict(X_test_sc)

print('Random Forest — Test Set')
results.append(evaluate('Random Forest', y_test, y_pred_rf_test))

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].scatter(y_test, y_pred_rf_test, alpha=0.5, color=PALETTE[1], s=20)
lims = [min(y_test.min(), y_pred_rf_test.min()), max(y_test.max(), y_pred_rf_test.max())]
axes[0].plot(lims, lims, 'r--', linewidth=1)
axes[0].set_xlabel('Actual AQI')
axes[0].set_ylabel('Predicted AQI')
axes[0].set_title('Random Forest — Actual vs Predicted')

# Feature importance
fi = pd.Series(rf.feature_importances_, index=FEATURE_COLS).sort_values(ascending=False)
axes[1].barh(fi.index[:15], fi.values[:15], color=PALETTE[1])
axes[1].set_title('Top 15 Feature Importances')
axes[1].set_xlabel('Importance')
axes[1].invert_yaxis()

plt.tight_layout()
plt.show()

# Train vs test to check overfitting
print(f'Train R² : {r2_score(y_train, y_pred_rf_train):.4f}')
print(f'Test  R² : {r2_score(y_test,  y_pred_rf_test):.4f}')

"""---
## 6. Model 3 — Support Vector Machine (SVR)
"""

svm = SVR(
    kernel='rbf',
    C=100,
    epsilon=0.5,
    gamma='scale'
)
svm.fit(X_train_sc, y_train)

y_pred_svm_train = svm.predict(X_train_sc)
y_pred_svm_test  = svm.predict(X_test_sc)

print('SVM (SVR) — Test Set')
results.append(evaluate('SVM (SVR)', y_test, y_pred_svm_test))

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].scatter(y_test, y_pred_svm_test, alpha=0.5, color=PALETTE[2], s=20)
lims = [min(y_test.min(), y_pred_svm_test.min()), max(y_test.max(), y_pred_svm_test.max())]
axes[0].plot(lims, lims, 'r--', linewidth=1)
axes[0].set_xlabel('Actual AQI')
axes[0].set_ylabel('Predicted AQI')
axes[0].set_title('SVM — Actual vs Predicted')

residuals_svm = y_test - y_pred_svm_test
axes[1].hist(residuals_svm, bins=25, color=PALETTE[2], edgecolor='white')
axes[1].set_title('SVM — Residual Distribution')
axes[1].set_xlabel('Residual')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""---
## 7. Model 4 — LSTM (Long Short-Term Memory)
"""

def build_lstm(n_features):
    model = Sequential([
        LSTM(128, return_sequences=True, input_shape=(1, n_features)),
        Dropout(0.2),
        LSTM(64, return_sequences=False),
        Dropout(0.2),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=1e-3), loss='mse', metrics=['mae'])
    return model

lstm_model = build_lstm(n_features)
lstm_model.summary()

callbacks = [
    EarlyStopping(patience=15, restore_best_weights=True, monitor='val_loss'),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=7, min_lr=1e-6)
]

lstm_history = lstm_model.fit(
    X_train_3d, y_train,
    validation_data=(X_val_3d, y_val),
    epochs=150,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

y_pred_lstm_test = lstm_model.predict(X_test_3d).flatten()

print('LSTM — Test Set')
results.append(evaluate('LSTM', y_test, y_pred_lstm_test))

# Training curves
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(lstm_history.history['loss'],     label='Train Loss', color=PALETTE[3])
axes[0].plot(lstm_history.history['val_loss'], label='Val Loss',   color=PALETTE[2], linestyle='--')
axes[0].set_title('LSTM — Loss Curve')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('MSE Loss')
axes[0].legend()

axes[1].scatter(y_test, y_pred_lstm_test, alpha=0.5, color=PALETTE[3], s=20)
lims = [min(y_test.min(), y_pred_lstm_test.min()), max(y_test.max(), y_pred_lstm_test.max())]
axes[1].plot(lims, lims, 'r--', linewidth=1)
axes[1].set_xlabel('Actual AQI')
axes[1].set_ylabel('Predicted AQI')
axes[1].set_title('LSTM — Actual vs Predicted')

plt.tight_layout()
plt.show()

"""---
## 8. Model 5 — ANN (Artificial Neural Network)
"""

def build_ann(n_features):
    """
    Deep feed-forward ANN:
      Input  →  Dense(256, ReLU) → BN → Dropout(0.3)
             →  Dense(128, ReLU) → BN → Dropout(0.2)
             →  Dense(64,  ReLU) → BN → Dropout(0.2)
             →  Dense(32,  ReLU)
             →  Dense(1)          ← linear output for regression
    """
    model = Sequential([
        Dense(256, activation='relu', input_shape=(n_features,)),
        BatchNormalization(),
        Dropout(0.3),

        Dense(128, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),

        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),

        Dense(32, activation='relu'),
        Dense(1)   # linear — no activation for regression
    ])
    model.compile(
        optimizer=Adam(learning_rate=1e-3),
        loss='mse',
        metrics=['mae']
    )
    return model

ann_model = build_ann(n_features)
ann_model.summary()

callbacks = [
    EarlyStopping(patience=15, restore_best_weights=True, monitor='val_loss'),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=7, min_lr=1e-6)
]

ann_history = ann_model.fit(
    X_train_sc, y_train,           # 2D input — no reshape needed
    validation_data=(X_val_sc, y_val),
    epochs=200,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

y_pred_ann_test = ann_model.predict(X_test_sc).flatten()

print('ANN — Test Set')
results.append(evaluate('ANN', y_test, y_pred_ann_test))

# Training curves
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(ann_history.history['loss'],     label='Train Loss', color=PALETTE[4])
axes[0].plot(ann_history.history['val_loss'], label='Val Loss',   color=PALETTE[2], linestyle='--')
axes[0].set_title('ANN — Loss Curve')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('MSE Loss')
axes[0].legend()

axes[1].scatter(y_test, y_pred_ann_test, alpha=0.5, color=PALETTE[4], s=20)
lims = [min(y_test.min(), y_pred_ann_test.min()), max(y_test.max(), y_pred_ann_test.max())]
axes[1].plot(lims, lims, 'r--', linewidth=1)
axes[1].set_xlabel('Actual AQI')
axes[1].set_ylabel('Predicted AQI')
axes[1].set_title('ANN — Actual vs Predicted')

plt.tight_layout()
plt.show()

"""---
## 9. Model Comparison & Evaluation
"""

results_df = pd.DataFrame(results)
results_df = results_df.set_index('Model')
results_df = results_df.round(4)

# Highlight best per metric
print('\n===== MODEL PERFORMANCE SUMMARY =====')
print(results_df.to_string())
print('\n--- Best per metric ---')
print(f"Best MAE  (lowest) : {results_df['MAE'].idxmin()}  ({results_df['MAE'].min():.3f})")
print(f"Best RMSE (lowest) : {results_df['RMSE'].idxmin()}  ({results_df['RMSE'].min():.3f})")
print(f"Best R²   (highest): {results_df['R2'].idxmax()}  ({results_df['R2'].max():.4f})")
print(f"Best MAPE (lowest) : {results_df['MAPE'].idxmin()}  ({results_df['MAPE'].min():.2f}%)")

# ── Bar chart comparison ─────────────────────────────────────────────────
metrics = ['MAE', 'RMSE', 'R2', 'MAPE']
fig, axes = plt.subplots(2, 2, figsize=(14, 9))
axes = axes.flatten()

for i, metric in enumerate(metrics):
    vals   = results_df[metric]
    best   = vals.idxmin() if metric != 'R2' else vals.idxmax()
    colors = [PALETTE[1] if m == best else PALETTE[0] for m in vals.index]
    bars   = axes[i].bar(vals.index, vals.values, color=colors, edgecolor='white', linewidth=0.5)
    for bar, val in zip(bars, vals.values):
        axes[i].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005 * vals.max(),
                     f'{val:.3f}', ha='center', va='bottom', fontsize=9)
    axes[i].set_title(f'{metric} Comparison  (green = best)', fontsize=12)
    axes[i].set_ylabel(metric)
    axes[i].tick_params(axis='x', rotation=15)

plt.suptitle('Model Performance Comparison — All Metrics', fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# ── Radar chart ─────────────────────────────────────────────────────────
from matplotlib.patches import FancyBboxPatch

# Normalise: higher = better for all axes (invert error metrics)
radar_df = results_df.copy()
for col in ['MAE', 'RMSE', 'MAPE']:
    radar_df[col] = 1 / (1 + radar_df[col])          # invert so bigger = better
# R2 already higher = better; normalise 0-1
for col in radar_df.columns:
    radar_df[col] = (radar_df[col] - radar_df[col].min()) / \
                    (radar_df[col].max() - radar_df[col].min() + 1e-9)

labels  = ['1/MAE', '1/RMSE', 'R²', '1/MAPE']
N       = len(labels)
angles  = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]

fig, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True))

for idx, (model_name, row) in enumerate(radar_df.iterrows()):
    values  = row.tolist() + row.tolist()[:1]
    ax.plot(angles, values, 'o-', linewidth=2, label=model_name, color=PALETTE[idx % len(PALETTE)])
    ax.fill(angles, values, alpha=0.08, color=PALETTE[idx % len(PALETTE)])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels, size=11)
ax.set_title('Radar — Normalised Performance\n(further from centre = better)', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1))
plt.tight_layout()
plt.show()

# ── Predicted vs Actual — all models side by side ───────────────────────
all_preds = {
    'Linear Regression': y_pred_lr_test,
    'Random Forest'    : y_pred_rf_test,
    'SVM (SVR)'        : y_pred_svm_test,
    'LSTM'             : y_pred_lstm_test,
    'ANN'              : y_pred_ann_test,
}

fig, axes = plt.subplots(1, 5, figsize=(20, 4), sharey=True)
for ax, (name, preds), color in zip(axes, all_preds.items(), PALETTE):
    ax.scatter(y_test, preds, alpha=0.45, s=15, color=color)
    lims = [min(y_test.min(), preds.min()), max(y_test.max(), preds.max())]
    ax.plot(lims, lims, 'r--', linewidth=1)
    ax.set_title(name, fontsize=10)
    ax.set_xlabel('Actual')
    r2 = r2_score(y_test, preds)
    ax.text(0.05, 0.92, f'R²={r2:.3f}', transform=ax.transAxes, fontsize=9,
            color='black', bbox=dict(boxstyle='round,pad=0.2', fc='white', alpha=0.7))
axes[0].set_ylabel('Predicted AQI')
plt.suptitle('Actual vs Predicted — All Models', fontsize=13)
plt.tight_layout()
plt.show()

# ── Residual box plots ───────────────────────────────────────────────────
residuals_all = {name: y_test - preds for name, preds in all_preds.items()}

fig, ax = plt.subplots(figsize=(11, 5))
bp = ax.boxplot(residuals_all.values(), labels=residuals_all.keys(),
                patch_artist=True, notch=False,
                medianprops=dict(color='black', linewidth=2))
for patch, color in zip(bp['boxes'], PALETTE):
    patch.set_facecolor(color)
    patch.set_alpha(0.65)
ax.axhline(0, color='red', linestyle='--', linewidth=1)
ax.set_title('Residual Distribution — All Models')
ax.set_ylabel('Residual (Actual − Predicted)')
ax.tick_params(axis='x', rotation=10)
plt.tight_layout()
plt.show()

"""---
## 10. Final Recommendation
"""

# ── Composite score (rank each metric, lower rank = better) ─────────────
rank_df = pd.DataFrame()
rank_df['MAE_rank']  = results_df['MAE'].rank(ascending=True)
rank_df['RMSE_rank'] = results_df['RMSE'].rank(ascending=True)
rank_df['R2_rank']   = results_df['R2'].rank(ascending=False)   # higher R2 = better
rank_df['MAPE_rank'] = results_df['MAPE'].rank(ascending=True)
rank_df['Composite_Score'] = rank_df.mean(axis=1)
rank_df = rank_df.sort_values('Composite_Score')

print('\n===== COMPOSITE RANKING (lower score = better) =====')
print(rank_df.to_string())

best_model = rank_df.index[0]
print(f'\n★  RECOMMENDED MODEL: {best_model}')

# ── Final summary table ──────────────────────────────
# The original `results_df` and `rank_df` have duplicate index labels ('LSTM'),
# causing a ValueError when trying to assign the 'Rank' column.
# We will recreate these DataFrames with unique model names for consistency.

# Recreate results_df from the global 'results' list, ensuring unique model names
temp_results_df = pd.DataFrame(results)

# Create unique model names by appending a number to duplicates
counts = {}
unique_model_names = []
for model_name in temp_results_df['Model']:
    if model_name in counts:
        counts[model_name] += 1
        unique_model_names.append(f'{model_name}_{counts[model_name]}')
    else:
        counts[model_name] = 0
        unique_model_names.append(model_name)

temp_results_df['UniqueModelName'] = unique_model_names
results_df_fixed = temp_results_df.set_index('UniqueModelName').drop(columns=['Model'])

# Recompute rank_df using the fixed results_df_fixed
rank_df_fixed = pd.DataFrame()
rank_df_fixed['MAE_rank']  = results_df_fixed['MAE'].rank(ascending=True)
rank_df_fixed['RMSE_rank'] = results_df_fixed['RMSE'].rank(ascending=True)
rank_df_fixed['R2_rank']   = results_df_fixed['R2'].rank(ascending=False)   # higher R2 = better
rank_df_fixed['MAPE_rank'] = results_df_fixed['MAPE'].rank(ascending=True)
rank_df_fixed['Composite_Score'] = rank_df_fixed.mean(axis=1)
rank_df_fixed = rank_df_fixed.sort_values('Composite_Score')

print('\n===== COMPOSITE RANKING (lower score = better) =====')
print(rank_df_fixed.to_string())

best_model_fixed = rank_df_fixed.index[0] # Get the name of the best model (now unique)
print(f'\n★  RECOMMENDED MODEL: {best_model_fixed}')

# Now, build the summary table using the fixed DataFrames
summary = results_df_fixed.copy()
summary['Rank'] = rank_df_fixed['Composite_Score'].rank().astype(int)
summary = summary.sort_values('Rank')

fig, ax = plt.subplots(figsize=(11, 3))
ax.axis('off')
table_data = [['Model', 'MAE', 'RMSE', 'R²', 'MAPE (%)', 'Rank']]
for model, row in summary.iterrows():
    # Use the unique model name from the index for display
    table_data.append([
        model,
        f"{row['MAE']:.3f}",
        f"{row['RMSE']:.3f}",
        f"{row['R2']:.4f}",
        f"{row['MAPE']:.2f}%",
        f"{int(row['Rank'])}"
    ])

tbl = ax.table(cellText=table_data[1:], colLabels=table_data[0],
               cellLoc='center', loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(11)
tbl.scale(1.3, 1.8)

# Header style
for j in range(len(table_data[0])):
    tbl[(0, j)].set_facecolor('#2C3E50')
    tbl[(0, j)].set_text_props(color='white', fontweight='bold')

# Highlight best row
# Find the row index of the best model using its unique name
best_row_idx = list(summary.index).index(best_model_fixed) + 1
for j in range(len(table_data[0])):
    tbl[(best_row_idx, j)].set_facecolor('#D5F5E3')

ax.set_title(f'Final Model Comparison  |  ★ Best: {best_model_fixed}', fontsize=13, pad=15)
plt.tight_layout()
plt.show()