# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ngwh6mjZyzKpoytV_a0oMZsy71l1oGF-
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

data = {
    'pm25': [15, 45, 12, 60, 22, 10],
    'pm10': [30, 80, 25, 110, 40, 20],
    'no2': [20, 55, 15, 70, 30, 12],
    'so2': [5, 15, 3, 20, 8, 2],
    'co': [0.5, 1.2, 0.3, 2.1, 0.8, 0.4],
    'o3': [30, 10, 35, 5, 25, 40],
    'temp': [18, 22, 17, 25, 20, 16],
    'humidity': [85, 70, 90, 60, 80, 92],
    'wind_speed': [5, 2, 6, 1, 4, 8],
    'target_pm25': [18, 48, 11, 65, 20, 9]
}

df = pd.DataFrame(data)

X = df.drop('target_pm25', axis=1)
y = df['target_pm25']
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

def calculate_aqi_label(val):
    if val <= 50: return "Excellent"
    if val <= 100: return "Good"
    if val <= 150: return "Lightly Polluted"
    if val <= 200: return "Moderately Polluted"
    return "Heavily Polluted"

print("--- Lima Air Quality Forecasting System (Full Parameters) ---")
try:
    pm25 = float(input("PM2.5 concentration (µg/m³): "))
    pm10 = float(input("PM10 concentration (µg/m³): "))
    no2  = float(input("NO2 concentration (ppb): "))
    so2  = float(input("SO2 concentration (ppb): "))
    co   = float(input("CO concentration (mg/m³): "))
    o3   = float(input("O3 concentration (ppb): "))

    temp = float(input("Temperature (°C): "))
    hum  = float(input("Humidity (%): "))
    wind = float(input("Wind Speed (km/h): "))

    features = np.array([[pm25, pm10, no2, so2, co, o3, temp, hum, wind]])

    prediction = model.predict(features)[0]

    print("\n" + "="*50)
    print(f"LIMA CITY FORECAST RESULTS")
    print("-" * 50)
    print(f"Current PM2.5 Status:    {calculate_aqi_label(pm25)}")
    print(f"Predicted PM2.5 (1hr):  {prediction:.2f} µg/m³")
    print(f"Predicted Condition:    {calculate_aqi_label(prediction)}")

    if hum > 85 and wind < 3:
        print("\nNote: High humidity and low wind detected. Pollutants are likely to remain trapped near the surface (Thermal Inversion).")
    print("="*50)

except ValueError:
    print("Error: Please enter valid numerical data for all fields.")

