# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1iaw1OBAdClsaTDVs-WuLyJDohREg2p
"""

import pandas as pd

# Load the Excel file into a pandas DataFrame
df = pd.read_excel('/content/Air_Quality_ML_Dataset(gurugram).xlsx')

# Display the first 5 rows of the DataFrame
display(df.head())

# Display basic information about the DataFrame, including data types and non-null values
display(df.info())

features = [
    'humidity_percent', 'dew_point_c', 'wind_gusts_kmh', 'precipitation_mm',
    'is_raining', 'heavy_rain', 'pressure_msl_hpa', 'cloud_cover_percent',
    'pm2_5_ugm3', 'pm10_ugm3', 'co_ugm3', 'no2_ugm3', 'so2_ugm3', 'o3_ugm3', 'dust_ugm3', 'aod'
]
target = 'AQI'

X = df[features]
y = df[target]

# Identify categorical columns that need one-hot encoding
categorical_cols = X.select_dtypes(include=['object', 'bool']).columns

# Apply one-hot encoding
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

# Display the first few rows of the processed features and their shape
display(X.head())
display(f"Shape of features (X): {X.shape}")
display(f"Shape of target (y): {y.shape}")

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
# Using a 80/20 split, with a random state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
display(f"X_train shape: {X_train.shape}")
display(f"X_test shape: {X_test.shape}")
display(f"y_train shape: {y_train.shape}")
display(f"y_test shape: {y_test.shape}")

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score

# Create a pipeline with StandardScaler and SVR
# StandardScaler is important for SVM as it is sensitive to feature scaling
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVR(kernel='rbf', C=1.0, epsilon=0.2)) # Using RBF kernel, C and epsilon are tunable hyperparameters
])

# Train the SVM model
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

display(f"Mean Squared Error (MSE): {mse:.2f}")
display(f"R-squared (R2): {r2:.2f}")

# Display the first few actual vs predicted values
results_df = pd.DataFrame({'Actual AQI': y_test, 'Predicted AQI': y_pred})
display(results_df.head())

import matplotlib.pyplot as plt
import seaborn as sns

# Set style for plots
sns.set_style("whitegrid")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel("Actual AQI")
plt.ylabel("Predicted AQI")
plt.title("Actual vs. Predicted AQI Values")
plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True)
plt.xlabel("Residuals (Actual - Predicted)")
plt.ylabel("Frequency")
plt.title("Distribution of Residuals")
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_pred, y=residuals, alpha=0.6)
plt.axhline(y=0, color='r', linestyle='--', lw=2)
plt.xlabel("Predicted AQI")
plt.ylabel("Residuals")
plt.title("Residuals vs. Predicted AQI")
plt.show()

import ipywidgets as widgets
from IPython.display import display, HTML
import pandas as pd

# Define the features that the model expects, in the correct order
# These should match the columns of X after one-hot encoding
feature_names = X.columns.tolist()

# Create input widgets for each feature
input_widgets = {}
for feature in feature_names:
    if 'is_raining' in feature or 'heavy_rain' in feature:
        # For boolean features, use Checkbox
        input_widgets[feature] = widgets.Checkbox(
            value=False,  # Default value
            description=feature.replace('_', ' ').title(),
            disabled=False,
            indent=False
        )
    else:
        # For numerical features, use FloatText
        input_widgets[feature] = widgets.FloatText(
            value=X[feature].mean(), # Default to mean of the training data
            description=feature.replace('_', ' ').title(),
            disabled=False
        )

# Create an output widget to display predictions
output_widget = widgets.Output()

# Define the prediction function
def predict_aqi(_):
    with output_widget:
        output_widget.clear_output()
        try:
            # Create a DataFrame from widget values
            input_data = {name: [widget.value] for name, widget in input_widgets.items()}
            input_df = pd.DataFrame(input_data)

            # Make prediction using the trained pipeline
            prediction = pipeline.predict(input_df)[0]

            display(HTML(f"<b><span style='font-size: 20px;'>Predicted AQI: {prediction:.2f}</span></b>"))
        except Exception as e:
            display(HTML(f"<span style='color: red;'>Error: {e}</span>"))

# Create a button for prediction
predict_button = widgets.Button(description="Predict AQI")
predict_button.on_click(predict_aqi)

# Arrange widgets in a VBox
gui_layout = widgets.VBox(
    [widgets.HBox([input_widgets[f] for f in feature_names[:4]]),
     widgets.HBox([input_widgets[f] for f in feature_names[4:8]]),
     widgets.HBox([input_widgets[f] for f in feature_names[8:12]]),
     widgets.HBox([input_widgets[f] for f in feature_names[12:]]),
     predict_button,
     output_widget]
)

display(gui_layout)